DROP IF TABLE EXISTS threads CASCADE;

CREATE TABLE threads (
  id SERIAL PRIMARY KEY NOT NULL,
  tweet_id INTEGER REFERENCES tweets(id) NOT NULL,
  user_id INTEGER REFERENCES users(id) NOT NULL,
  body TEXT NOT NULL,
  date TIMESTAMP NOT NULL
);